/**
 * Cinematic sky / atmosphere presets for Overview (daylight-first).
 * Colours are linear-ish RGB used by the sky shader (toneMapped: false).
 */

export const SKY_PRESETS = {
  calmRealistic: {
    label: "Calm Realistic",
    top: "#1a4a8c",
    mid: "#4a7eb8",
    horizon: "#b8d4e8",
    haze: "#d8e8f2",
    sunColor: "#ffe6c8",
    hemiSky: "#d5e4ee",
    hemiGround: "#6a5e4c",
    fogColor: "#889a78",
    // Live-like: soft sparse clouds — sky blue stays dominant
    cloudDensity: 0.22,
    cloudContrast: 0.5,
    animStrength: 0.24,
    atmosphere: 0.48,
    horizonHaze: 0.4,
    sunIntensity: 1.48,
    hemiIntensity: 0.98,
    fillIntensity: 0.28,
    sunWarmth: 0.14,
    exposure: 1.2,
  },
  clearBlueDay: {
    label: "Clear Blue Day",
    top: "#0e3a7a",
    mid: "#3a78c4",
    horizon: "#a8cce8",
    haze: "#c8e0f0",
    sunColor: "#fff2dc",
    hemiSky: "#e0eef8",
    hemiGround: "#7a7058",
    fogColor: "#8aa080",
    cloudDensity: 0.1,
    cloudContrast: 0.35,
    animStrength: 0.16,
    atmosphere: 0.36,
    horizonHaze: 0.28,
    sunIntensity: 1.58,
    hemiIntensity: 1.04,
    fillIntensity: 0.26,
    sunWarmth: 0.08,
    exposure: 1.24,
  },
  cinematicClouds: {
    label: "Cinematic Clouds",
    top: "#1e4578",
    mid: "#5a88b8",
    horizon: "#c4d8e8",
    haze: "#e0ecf4",
    sunColor: "#ffdcb0",
    hemiSky: "#c8d8e8",
    hemiGround: "#6a5848",
    fogColor: "#7a8e82",
    cloudDensity: 0.55,
    cloudContrast: 0.62,
    animStrength: 0.36,
    atmosphere: 0.58,
    horizonHaze: 0.52,
    sunIntensity: 1.3,
    hemiIntensity: 0.9,
    fillIntensity: 0.36,
    sunWarmth: 0.2,
    exposure: 1.14,
  },
  floodWeather: {
    label: "Flood Weather",
    top: "#2a4058",
    mid: "#5a7088",
    horizon: "#a8b8c4",
    haze: "#c0ccd4",
    sunColor: "#d8dce0",
    hemiSky: "#b0c0cc",
    hemiGround: "#5a5850",
    fogColor: "#6e7e78",
    cloudDensity: 0.7,
    cloudContrast: 0.58,
    animStrength: 0.32,
    atmosphere: 0.7,
    horizonHaze: 0.68,
    sunIntensity: 1.08,
    hemiIntensity: 0.8,
    fillIntensity: 0.42,
    sunWarmth: 0.05,
    exposure: 1.06,
  },
  goldenHour: {
    label: "Golden Hour",
    top: "#2a5088",
    mid: "#6a90b8",
    horizon: "#f0c898",
    haze: "#f8e0c0",
    sunColor: "#ffb060",
    hemiSky: "#f0d8b8",
    hemiGround: "#8a6040",
    fogColor: "#a09070",
    cloudDensity: 0.32,
    cloudContrast: 0.52,
    animStrength: 0.28,
    atmosphere: 0.52,
    horizonHaze: 0.48,
    sunIntensity: 1.38,
    hemiIntensity: 0.92,
    fillIntensity: 0.4,
    sunWarmth: 0.52,
    exposure: 1.2,
  },
};

export const DEFAULT_SKY_PRESET = "calmRealistic";

export function getSkyPreset(name) {
  return SKY_PRESETS[name] || SKY_PRESETS[DEFAULT_SKY_PRESET];
}
