/** Calm cinematic river presets — tuned for smooth sine-wave surface (no noise blobs). */

export const WATER_PRESETS = {
  calmRealistic: {
    label: "Calm Realistic River",
    waterAnimEnabled: true,
    waterOverallSpeed: 0.55,
    primaryWaveAmplitude: 0.06,
    primaryWaveSpeed: 0.035,
    secondaryWaveAmplitude: 0.035,
    secondaryWaveSpeed: 0.05,
    rippleAmplitude: 0.015,
    rippleSpeed: 0.07,
    flowSpeed: 0.45,
    flowStrength: 0.85,
    waterOpacity: 0.88,
    reflectionStrength: 0.68,
    waveHighlight: 0.85,
    shallowColor: "#4fc8eb",
    deepColor: "#07529d",
  },
  glassyCalm: {
    label: "Glassy Calm",
    waterAnimEnabled: true,
    waterOverallSpeed: 0.32,
    primaryWaveAmplitude: 0.025,
    primaryWaveSpeed: 0.02,
    secondaryWaveAmplitude: 0.012,
    secondaryWaveSpeed: 0.028,
    rippleAmplitude: 0.006,
    rippleSpeed: 0.04,
    flowSpeed: 0.28,
    flowStrength: 0.5,
    waterOpacity: 0.92,
    reflectionStrength: 0.72,
    waveHighlight: 0.45,
    shallowColor: "#83dcf2",
    deepColor: "#1d69ae",
  },
  naturalRiver: {
    label: "Natural River",
    waterAnimEnabled: true,
    waterOverallSpeed: 0.62,
    primaryWaveAmplitude: 0.075,
    primaryWaveSpeed: 0.04,
    secondaryWaveAmplitude: 0.045,
    secondaryWaveSpeed: 0.06,
    rippleAmplitude: 0.02,
    rippleSpeed: 0.085,
    flowSpeed: 0.55,
    flowStrength: 1.0,
    waterOpacity: 0.94,
    reflectionStrength: 0.52,
    waveHighlight: 0.82,
    shallowColor: "#3fc5e8",
    deepColor: "#064c97",
  },
  windRipples: {
    label: "Wind Ripples",
    waterAnimEnabled: true,
    waterOverallSpeed: 0.58,
    primaryWaveAmplitude: 0.045,
    primaryWaveSpeed: 0.03,
    secondaryWaveAmplitude: 0.028,
    secondaryWaveSpeed: 0.045,
    rippleAmplitude: 0.032,
    rippleSpeed: 0.1,
    flowSpeed: 0.4,
    flowStrength: 0.75,
    waterOpacity: 0.92,
    reflectionStrength: 0.58,
    waveHighlight: 0.9,
    shallowColor: "#58c9e9",
    deepColor: "#0b579f",
  },
  cinematic: {
    label: "Cinematic",
    waterAnimEnabled: true,
    waterOverallSpeed: 0.48,
    primaryWaveAmplitude: 0.07,
    primaryWaveSpeed: 0.032,
    secondaryWaveAmplitude: 0.04,
    secondaryWaveSpeed: 0.048,
    rippleAmplitude: 0.018,
    rippleSpeed: 0.065,
    flowSpeed: 0.42,
    flowStrength: 0.9,
    waterOpacity: 0.95,
    reflectionStrength: 0.72,
    waveHighlight: 0.88,
    shallowColor: "#48c4eb",
    deepColor: "#063f86",
  },
};

export const DEFAULT_WATER_PRESET = "calmRealistic";
