export const state = {
  playing: false,
  pathT: 0,
  pathDuration: 140,
  journeyT: 0,
  journeyDuration: 140,
  flowSpeed: 0.85,
  flowVisibility: 1,
  waterOpacity: 0.78,
  depthExaggeration: 2,
  showWater: true,
  showBathymetry: true,
  showVegetation: true,
  showUrban: true,
  showBridges: true,
  showBridgeNames: false,
  showTerrain: true,
  showOsmTrees: true,
  showOsmRoads: true,
  showOsmBuildings: true,
  showOsmAlignment: false,
  showLayers: false,
  inspectMode: false,
  showValidation: false,
  showWaterDebug: false,
  showFish: true,
  showFishDebug: true,
  showChainage: true,
  /** Show chainage text on every marker (Layers → Chainage toolkit). */
  showChainageLabels: false,
  /** "station" = 0+000 style · "meters" = 12400 m */
  chainageLabelMode: "station",
  /** Selected chainage meters (click highlight). */
  selectedChainageMeters: null,
  /** True while hovering the selected chainage (suppresses water-depth tip). */
  chainageTipActive: false,
  cinematicActive: false,
  cinematicPaused: false,
  cinematicProgress: 0,
  cinematicPhase: "idle",
  cinematicFishBoost: false,
  cinematicJumpCue: false,
  cinematicUnderwater: false,
  cinematicFishScene: false,
  cinematicJumpSequence: false,
  cinematicJumpBudget: 0,
  cinematicFishingPointFocus: null,
  validationStats: null,
  cameraMode: "overview",
  visualMode: "landscape",
  elapsed: 0,
  hover: null,
};
